apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-smoke-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.10.0
    helm:
      values: |
        service:
          type: LoadBalancer
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-smoke
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
